/** Gambar motif hasil pindai buku Profil Produk Unggulan Sasirangan Kalsel (2024). */
export const motifImages: Record<string, string> = {
  "bayam-raja": "/img/motif/bayam-raja.jpg",
  "berlian": "/img/motif/berlian.jpg",
  "bintang-behambur": "/img/motif/bintang-behambur.jpg",
  "daun-jaruju": "/img/motif/daun-jaruju.jpg",
  "daun-katu": "/img/motif/daun-katu.jpg",
  "gelombang": "/img/motif/gelombang.jpg",
  "gigi-haruan": "/img/motif/gigi-haruan.jpg",
  "gradasi": "/img/motif/gradasi.jpg",
  "hiris-gagatas": "/img/motif/hiris-gagatas.jpg",
  "hiris-pudak": "/img/motif/hiris-pudak.jpg",
  "jajumputan": "/img/motif/jajumputan.jpg",
  "kambang-sakaki": "/img/motif/kambang-sakaki.jpg",
  "kangkung-kaombakan": "/img/motif/kangkung-kaombakan.jpg",
  "kembang-kacang": "/img/motif/kembang-kacang.jpg",
  "kembang-tampuk-manggis": "/img/motif/kembang-tampuk-manggis.jpg",
  "ketupat": "/img/motif/ketupat.jpg",
  "kulat-karikit": "/img/motif/kulat-karikit.jpg",
  "mayang-maurai": "/img/motif/mayang-maurai.jpg",
  "naga-balimbur": "/img/motif/naga-balimbur.jpg",
  "ombak-sinapur-karang": "/img/motif/ombak-sinapur-karang.jpg",
  "pelangi": "/img/motif/pelangi.jpg",
  "ramak-sahang": "/img/motif/ramak-sahang.jpg",
  "sarigading": "/img/motif/sarigading.jpg",
  "saringkel-pandan": "/img/motif/saringkel-pandan.jpg",
  "sasirangan-bordir": "/img/motif/sasirangan-bordir.jpg",
  "turun-dayang": "/img/motif/turun-dayang.jpg",
  "ular-lidi": "/img/motif/ular-lidi.jpg",
};
