/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColorLabRouteImport } from './routes/color-lab'
import { Route as DesignerRouteImport } from './routes/designer'
import { Route as KuisRouteImport } from './routes/kuis'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as MotifIndexRouteImport } from './routes/motif.index'
import { Route as MotifSlugRouteImport } from './routes/motif.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorLabRoute = ColorLabRouteImport.update({
  id: '/color-lab',
  path: '/color-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerRoute = DesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => rootRouteImport,
} as any)
const KuisRoute = KuisRouteImport.update({
  id: '/kuis',
  path: '/kuis',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const MotifIndexRoute = MotifIndexRouteImport.update({
  id: '/motif/',
  path: '/motif/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotifSlugRoute = MotifSlugRouteImport.update({
  id: '/motif/$slug',
  path: '/motif/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/color-lab': typeof ColorLabRoute
  '/designer': typeof DesignerRoute
  '/kuis': typeof KuisRoute
  '/tutorial': typeof TutorialRoute
  '/motif/$slug': typeof MotifSlugRoute
  '/motif/': typeof MotifIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/color-lab': typeof ColorLabRoute
  '/designer': typeof DesignerRoute
  '/kuis': typeof KuisRoute
  '/tutorial': typeof TutorialRoute
  '/motif/$slug': typeof MotifSlugRoute
  '/motif': typeof MotifIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/color-lab': typeof ColorLabRoute
  '/designer': typeof DesignerRoute
  '/kuis': typeof KuisRoute
  '/tutorial': typeof TutorialRoute
  '/motif/$slug': typeof MotifSlugRoute
  '/motif/': typeof MotifIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/color-lab'
    | '/designer'
    | '/kuis'
    | '/tutorial'
    | '/motif/$slug'
    | '/motif/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/color-lab'
    | '/designer'
    | '/kuis'
    | '/tutorial'
    | '/motif/$slug'
    | '/motif'
  id:
    | '__root__'
    | '/'
    | '/color-lab'
    | '/designer'
    | '/kuis'
    | '/tutorial'
    | '/motif/$slug'
    | '/motif/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorLabRoute: typeof ColorLabRoute
  DesignerRoute: typeof DesignerRoute
  KuisRoute: typeof KuisRoute
  TutorialRoute: typeof TutorialRoute
  MotifSlugRoute: typeof MotifSlugRoute
  MotifIndexRoute: typeof MotifIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-lab': {
      id: '/color-lab'
      path: '/color-lab'
      fullPath: '/color-lab'
      preLoaderRoute: typeof ColorLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer': {
      id: '/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof DesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuis': {
      id: '/kuis'
      path: '/kuis'
      fullPath: '/kuis'
      preLoaderRoute: typeof KuisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motif/': {
      id: '/motif/'
      path: '/motif'
      fullPath: '/motif/'
      preLoaderRoute: typeof MotifIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motif/$slug': {
      id: '/motif/$slug'
      path: '/motif/$slug'
      fullPath: '/motif/$slug'
      preLoaderRoute: typeof MotifSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorLabRoute: ColorLabRoute,
  DesignerRoute: DesignerRoute,
  KuisRoute: KuisRoute,
  TutorialRoute: TutorialRoute,
  MotifSlugRoute: MotifSlugRoute,
  MotifIndexRoute: MotifIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
